<?php

return [
    'otp_expiry_minutes' => (int) env('OTP_EXPIRY_MINUTES', 10),
    'otp_max_attempts' => (int) env('OTP_MAX_ATTEMPTS', 3),
    'otp_bypass_code' => env('OTP_BYPASS_CODE'),
    'fne_api_url' => env('FNE_API_URL', ''),
    'fne_test_url' => env('FNE_TEST_URL', 'http://54.247.95.108/ws'),
    'countries' => [
        'SN' => ['name' => 'Sénégal',       'prefix' => '+221', 'label' => 'SEN (+221)'],
        'CI' => ['name' => "Côte d'Ivoire", 'prefix' => '+225', 'label' => 'CIV (+225)'],
    ],

    'phone_countries' => [
        // ── Afrique de l'Ouest (CEDEAO) ──
        'SN' => ['name' => 'Sénégal',           'prefix' => '+221', 'label' => 'SEN (+221)'],
        'CI' => ['name' => "Côte d'Ivoire",     'prefix' => '+225', 'label' => 'CIV (+225)'],
        'ML' => ['name' => 'Mali',               'prefix' => '+223', 'label' => 'MLI (+223)'],
        'GN' => ['name' => 'Guinée',             'prefix' => '+224', 'label' => 'GIN (+224)'],
        'BF' => ['name' => 'Burkina Faso',       'prefix' => '+226', 'label' => 'BFA (+226)'],
        'NE' => ['name' => 'Niger',              'prefix' => '+227', 'label' => 'NER (+227)'],
        'TG' => ['name' => 'Togo',               'prefix' => '+228', 'label' => 'TGO (+228)'],
        'BJ' => ['name' => 'Bénin',              'prefix' => '+229', 'label' => 'BEN (+229)'],
        'MR' => ['name' => 'Mauritanie',         'prefix' => '+222', 'label' => 'MRT (+222)'],
        'GH' => ['name' => 'Ghana',              'prefix' => '+233', 'label' => 'GHA (+233)'],
        'NG' => ['name' => 'Nigeria',            'prefix' => '+234', 'label' => 'NGA (+234)'],
        'GM' => ['name' => 'Gambie',             'prefix' => '+220', 'label' => 'GMB (+220)'],
        'GW' => ['name' => 'Guinée-Bissau',      'prefix' => '+245', 'label' => 'GNB (+245)'],
        'SL' => ['name' => 'Sierra Leone',       'prefix' => '+232', 'label' => 'SLE (+232)'],
        'LR' => ['name' => 'Liberia',            'prefix' => '+231', 'label' => 'LBR (+231)'],
        'CV' => ['name' => 'Cap-Vert',           'prefix' => '+238', 'label' => 'CPV (+238)'],

        // ── Afrique Centrale ──
        'CM' => ['name' => 'Cameroun',           'prefix' => '+237', 'label' => 'CMR (+237)'],
        'GA' => ['name' => 'Gabon',              'prefix' => '+241', 'label' => 'GAB (+241)'],
        'CG' => ['name' => 'Congo-Brazzaville',  'prefix' => '+242', 'label' => 'COG (+242)'],
        'CD' => ['name' => 'Congo-Kinshasa',     'prefix' => '+243', 'label' => 'COD (+243)'],
        'CF' => ['name' => 'Centrafrique',       'prefix' => '+236', 'label' => 'CAF (+236)'],
        'TD' => ['name' => 'Tchad',              'prefix' => '+235', 'label' => 'TCD (+235)'],
        'GQ' => ['name' => 'Guinée équatoriale', 'prefix' => '+240', 'label' => 'GNQ (+240)'],
        'ST' => ['name' => 'Sao Tomé-et-Principe', 'prefix' => '+239', 'label' => 'STP (+239)'],

        // ── Afrique de l'Est ──
        'KE' => ['name' => 'Kenya',              'prefix' => '+254', 'label' => 'KEN (+254)'],
        'TZ' => ['name' => 'Tanzanie',           'prefix' => '+255', 'label' => 'TZA (+255)'],
        'UG' => ['name' => 'Ouganda',            'prefix' => '+256', 'label' => 'UGA (+256)'],
        'RW' => ['name' => 'Rwanda',             'prefix' => '+250', 'label' => 'RWA (+250)'],
        'BI' => ['name' => 'Burundi',            'prefix' => '+257', 'label' => 'BDI (+257)'],
        'ET' => ['name' => 'Éthiopie',           'prefix' => '+251', 'label' => 'ETH (+251)'],
        'DJ' => ['name' => 'Djibouti',           'prefix' => '+253', 'label' => 'DJI (+253)'],
        'SO' => ['name' => 'Somalie',            'prefix' => '+252', 'label' => 'SOM (+252)'],
        'ER' => ['name' => 'Érythrée',           'prefix' => '+291', 'label' => 'ERI (+291)'],
        'SD' => ['name' => 'Soudan',             'prefix' => '+249', 'label' => 'SDN (+249)'],
        'SS' => ['name' => 'Soudan du Sud',      'prefix' => '+211', 'label' => 'SSD (+211)'],

        // ── Afrique Australe ──
        'ZA' => ['name' => 'Afrique du Sud',     'prefix' => '+27',  'label' => 'ZAF (+27)'],
        'MZ' => ['name' => 'Mozambique',         'prefix' => '+258', 'label' => 'MOZ (+258)'],
        'ZM' => ['name' => 'Zambie',             'prefix' => '+260', 'label' => 'ZMB (+260)'],
        'ZW' => ['name' => 'Zimbabwe',           'prefix' => '+263', 'label' => 'ZWE (+263)'],
        'MW' => ['name' => 'Malawi',             'prefix' => '+265', 'label' => 'MWI (+265)'],
        'BW' => ['name' => 'Botswana',           'prefix' => '+267', 'label' => 'BWA (+267)'],
        'NA' => ['name' => 'Namibie',            'prefix' => '+264', 'label' => 'NAM (+264)'],
        'SZ' => ['name' => 'Eswatini',           'prefix' => '+268', 'label' => 'SWZ (+268)'],
        'LS' => ['name' => 'Lesotho',            'prefix' => '+266', 'label' => 'LSO (+266)'],
        'AO' => ['name' => 'Angola',             'prefix' => '+244', 'label' => 'AGO (+244)'],
        'MG' => ['name' => 'Madagascar',         'prefix' => '+261', 'label' => 'MDG (+261)'],
        'MU' => ['name' => 'Maurice',            'prefix' => '+230', 'label' => 'MUS (+230)'],
        'KM' => ['name' => 'Comores',            'prefix' => '+269', 'label' => 'COM (+269)'],
        'SC' => ['name' => 'Seychelles',         'prefix' => '+248', 'label' => 'SYC (+248)'],

        // ── Afrique du Nord ──
        'MA' => ['name' => 'Maroc',              'prefix' => '+212', 'label' => 'MAR (+212)'],
        'DZ' => ['name' => 'Algérie',            'prefix' => '+213', 'label' => 'DZA (+213)'],
        'TN' => ['name' => 'Tunisie',            'prefix' => '+216', 'label' => 'TUN (+216)'],
        'LY' => ['name' => 'Libye',              'prefix' => '+218', 'label' => 'LBY (+218)'],
        'EG' => ['name' => 'Égypte',             'prefix' => '+20',  'label' => 'EGY (+20)'],

        // ── Europe ──
        'FR' => ['name' => 'France',             'prefix' => '+33',  'label' => 'FRA (+33)'],
        'BE' => ['name' => 'Belgique',           'prefix' => '+32',  'label' => 'BEL (+32)'],
        'CH' => ['name' => 'Suisse',             'prefix' => '+41',  'label' => 'CHE (+41)'],
        'ES' => ['name' => 'Espagne',            'prefix' => '+34',  'label' => 'ESP (+34)'],
        'PT' => ['name' => 'Portugal',           'prefix' => '+351', 'label' => 'PRT (+351)'],
        'DE' => ['name' => 'Allemagne',          'prefix' => '+49',  'label' => 'DEU (+49)'],
        'IT' => ['name' => 'Italie',             'prefix' => '+39',  'label' => 'ITA (+39)'],
        'GB' => ['name' => 'Royaume-Uni',        'prefix' => '+44',  'label' => 'GBR (+44)'],
        'NL' => ['name' => 'Pays-Bas',           'prefix' => '+31',  'label' => 'NLD (+31)'],
        'LU' => ['name' => 'Luxembourg',         'prefix' => '+352', 'label' => 'LUX (+352)'],
        'AT' => ['name' => 'Autriche',           'prefix' => '+43',  'label' => 'AUT (+43)'],
        'IE' => ['name' => 'Irlande',            'prefix' => '+353', 'label' => 'IRL (+353)'],
        'SE' => ['name' => 'Suède',              'prefix' => '+46',  'label' => 'SWE (+46)'],
        'NO' => ['name' => 'Norvège',            'prefix' => '+47',  'label' => 'NOR (+47)'],
        'DK' => ['name' => 'Danemark',           'prefix' => '+45',  'label' => 'DNK (+45)'],
        'FI' => ['name' => 'Finlande',           'prefix' => '+358', 'label' => 'FIN (+358)'],
        'PL' => ['name' => 'Pologne',            'prefix' => '+48',  'label' => 'POL (+48)'],
        'CZ' => ['name' => 'Tchéquie',           'prefix' => '+420', 'label' => 'CZE (+420)'],
        'RO' => ['name' => 'Roumanie',           'prefix' => '+40',  'label' => 'ROU (+40)'],
        'GR' => ['name' => 'Grèce',              'prefix' => '+30',  'label' => 'GRC (+30)'],
        'HU' => ['name' => 'Hongrie',            'prefix' => '+36',  'label' => 'HUN (+36)'],
        'HR' => ['name' => 'Croatie',            'prefix' => '+385', 'label' => 'HRV (+385)'],
        'BG' => ['name' => 'Bulgarie',           'prefix' => '+359', 'label' => 'BGR (+359)'],
        'SK' => ['name' => 'Slovaquie',          'prefix' => '+421', 'label' => 'SVK (+421)'],
        'SI' => ['name' => 'Slovénie',           'prefix' => '+386', 'label' => 'SVN (+386)'],
        'RS' => ['name' => 'Serbie',             'prefix' => '+381', 'label' => 'SRB (+381)'],
        'BA' => ['name' => 'Bosnie-Herzégovine', 'prefix' => '+387', 'label' => 'BIH (+387)'],
        'AL' => ['name' => 'Albanie',            'prefix' => '+355', 'label' => 'ALB (+355)'],
        'MK' => ['name' => 'Macédoine du Nord',  'prefix' => '+389', 'label' => 'MKD (+389)'],
        'ME' => ['name' => 'Monténégro',         'prefix' => '+382', 'label' => 'MNE (+382)'],
        'MD' => ['name' => 'Moldavie',           'prefix' => '+373', 'label' => 'MDA (+373)'],
        'UA' => ['name' => 'Ukraine',            'prefix' => '+380', 'label' => 'UKR (+380)'],
        'BY' => ['name' => 'Biélorussie',        'prefix' => '+375', 'label' => 'BLR (+375)'],
        'RU' => ['name' => 'Russie',             'prefix' => '+7',   'label' => 'RUS (+7)'],
        'TR' => ['name' => 'Turquie',            'prefix' => '+90',  'label' => 'TUR (+90)'],
        'CY' => ['name' => 'Chypre',             'prefix' => '+357', 'label' => 'CYP (+357)'],
        'MT' => ['name' => 'Malte',              'prefix' => '+356', 'label' => 'MLT (+356)'],
        'IS' => ['name' => 'Islande',            'prefix' => '+354', 'label' => 'ISL (+354)'],
        'EE' => ['name' => 'Estonie',            'prefix' => '+372', 'label' => 'EST (+372)'],
        'LV' => ['name' => 'Lettonie',           'prefix' => '+371', 'label' => 'LVA (+371)'],
        'LT' => ['name' => 'Lituanie',           'prefix' => '+370', 'label' => 'LTU (+370)'],

        // ── Amérique du Nord ──
        'US' => ['name' => 'États-Unis',         'prefix' => '+1',   'label' => 'USA (+1)'],
        'CA' => ['name' => 'Canada',             'prefix' => '+1',   'label' => 'CAN (+1)'],
        'MX' => ['name' => 'Mexique',            'prefix' => '+52',  'label' => 'MEX (+52)'],

        // ── Amérique Centrale & Caraïbes ──
        'HT' => ['name' => 'Haïti',              'prefix' => '+509', 'label' => 'HTI (+509)'],
        'DO' => ['name' => 'Rép. dominicaine',   'prefix' => '+1',   'label' => 'DOM (+1)'],
        'CU' => ['name' => 'Cuba',               'prefix' => '+53',  'label' => 'CUB (+53)'],
        'JM' => ['name' => 'Jamaïque',           'prefix' => '+1',   'label' => 'JAM (+1)'],
        'TT' => ['name' => 'Trinité-et-Tobago',  'prefix' => '+1',   'label' => 'TTO (+1)'],
        'PA' => ['name' => 'Panama',             'prefix' => '+507', 'label' => 'PAN (+507)'],
        'CR' => ['name' => 'Costa Rica',         'prefix' => '+506', 'label' => 'CRI (+506)'],
        'GT' => ['name' => 'Guatemala',          'prefix' => '+502', 'label' => 'GTM (+502)'],
        'HN' => ['name' => 'Honduras',           'prefix' => '+504', 'label' => 'HND (+504)'],
        'SV' => ['name' => 'Salvador',           'prefix' => '+503', 'label' => 'SLV (+503)'],
        'NI' => ['name' => 'Nicaragua',          'prefix' => '+505', 'label' => 'NIC (+505)'],

        // ── Amérique du Sud ──
        'BR' => ['name' => 'Brésil',             'prefix' => '+55',  'label' => 'BRA (+55)'],
        'AR' => ['name' => 'Argentine',          'prefix' => '+54',  'label' => 'ARG (+54)'],
        'CO' => ['name' => 'Colombie',           'prefix' => '+57',  'label' => 'COL (+57)'],
        'CL' => ['name' => 'Chili',              'prefix' => '+56',  'label' => 'CHL (+56)'],
        'PE' => ['name' => 'Pérou',              'prefix' => '+51',  'label' => 'PER (+51)'],
        'VE' => ['name' => 'Venezuela',          'prefix' => '+58',  'label' => 'VEN (+58)'],
        'EC' => ['name' => 'Équateur',           'prefix' => '+593', 'label' => 'ECU (+593)'],
        'BO' => ['name' => 'Bolivie',            'prefix' => '+591', 'label' => 'BOL (+591)'],
        'PY' => ['name' => 'Paraguay',           'prefix' => '+595', 'label' => 'PRY (+595)'],
        'UY' => ['name' => 'Uruguay',            'prefix' => '+598', 'label' => 'URY (+598)'],
        'GY' => ['name' => 'Guyana',             'prefix' => '+592', 'label' => 'GUY (+592)'],
        'SR' => ['name' => 'Suriname',           'prefix' => '+597', 'label' => 'SUR (+597)'],
        'GF' => ['name' => 'Guyane française',   'prefix' => '+594', 'label' => 'GUF (+594)'],

        // ── Moyen-Orient ──
        'SA' => ['name' => 'Arabie saoudite',    'prefix' => '+966', 'label' => 'SAU (+966)'],
        'AE' => ['name' => 'Émirats arabes unis', 'prefix' => '+971', 'label' => 'ARE (+971)'],
        'QA' => ['name' => 'Qatar',              'prefix' => '+974', 'label' => 'QAT (+974)'],
        'KW' => ['name' => 'Koweït',             'prefix' => '+965', 'label' => 'KWT (+965)'],
        'BH' => ['name' => 'Bahreïn',            'prefix' => '+973', 'label' => 'BHR (+973)'],
        'OM' => ['name' => 'Oman',               'prefix' => '+968', 'label' => 'OMN (+968)'],
        'YE' => ['name' => 'Yémen',              'prefix' => '+967', 'label' => 'YEM (+967)'],
        'IQ' => ['name' => 'Irak',               'prefix' => '+964', 'label' => 'IRQ (+964)'],
        'IR' => ['name' => 'Iran',               'prefix' => '+98',  'label' => 'IRN (+98)'],
        'JO' => ['name' => 'Jordanie',           'prefix' => '+962', 'label' => 'JOR (+962)'],
        'LB' => ['name' => 'Liban',              'prefix' => '+961', 'label' => 'LBN (+961)'],
        'SY' => ['name' => 'Syrie',              'prefix' => '+963', 'label' => 'SYR (+963)'],
        'PS' => ['name' => 'Palestine',          'prefix' => '+970', 'label' => 'PSE (+970)'],
        'IL' => ['name' => 'Israël',             'prefix' => '+972', 'label' => 'ISR (+972)'],

        // ── Asie ──
        'CN' => ['name' => 'Chine',              'prefix' => '+86',  'label' => 'CHN (+86)'],
        'JP' => ['name' => 'Japon',              'prefix' => '+81',  'label' => 'JPN (+81)'],
        'KR' => ['name' => 'Corée du Sud',       'prefix' => '+82',  'label' => 'KOR (+82)'],
        'IN' => ['name' => 'Inde',               'prefix' => '+91',  'label' => 'IND (+91)'],
        'PK' => ['name' => 'Pakistan',           'prefix' => '+92',  'label' => 'PAK (+92)'],
        'BD' => ['name' => 'Bangladesh',         'prefix' => '+880', 'label' => 'BGD (+880)'],
        'LK' => ['name' => 'Sri Lanka',          'prefix' => '+94',  'label' => 'LKA (+94)'],
        'NP' => ['name' => 'Népal',              'prefix' => '+977', 'label' => 'NPL (+977)'],
        'MM' => ['name' => 'Myanmar',            'prefix' => '+95',  'label' => 'MMR (+95)'],
        'TH' => ['name' => 'Thaïlande',         'prefix' => '+66',  'label' => 'THA (+66)'],
        'VN' => ['name' => 'Viêt Nam',           'prefix' => '+84',  'label' => 'VNM (+84)'],
        'KH' => ['name' => 'Cambodge',           'prefix' => '+855', 'label' => 'KHM (+855)'],
        'LA' => ['name' => 'Laos',               'prefix' => '+856', 'label' => 'LAO (+856)'],
        'MY' => ['name' => 'Malaisie',           'prefix' => '+60',  'label' => 'MYS (+60)'],
        'SG' => ['name' => 'Singapour',          'prefix' => '+65',  'label' => 'SGP (+65)'],
        'ID' => ['name' => 'Indonésie',          'prefix' => '+62',  'label' => 'IDN (+62)'],
        'PH' => ['name' => 'Philippines',        'prefix' => '+63',  'label' => 'PHL (+63)'],
        'TW' => ['name' => 'Taïwan',             'prefix' => '+886', 'label' => 'TWN (+886)'],
        'HK' => ['name' => 'Hong Kong',          'prefix' => '+852', 'label' => 'HKG (+852)'],
        'MN' => ['name' => 'Mongolie',           'prefix' => '+976', 'label' => 'MNG (+976)'],
        'AF' => ['name' => 'Afghanistan',        'prefix' => '+93',  'label' => 'AFG (+93)'],
        'UZ' => ['name' => 'Ouzbékistan',        'prefix' => '+998', 'label' => 'UZB (+998)'],
        'KZ' => ['name' => 'Kazakhstan',         'prefix' => '+7',   'label' => 'KAZ (+7)'],
        'GE' => ['name' => 'Géorgie',            'prefix' => '+995', 'label' => 'GEO (+995)'],
        'AM' => ['name' => 'Arménie',            'prefix' => '+374', 'label' => 'ARM (+374)'],
        'AZ' => ['name' => 'Azerbaïdjan',        'prefix' => '+994', 'label' => 'AZE (+994)'],

        // ── Océanie ──
        'AU' => ['name' => 'Australie',          'prefix' => '+61',  'label' => 'AUS (+61)'],
        'NZ' => ['name' => 'Nouvelle-Zélande',   'prefix' => '+64',  'label' => 'NZL (+64)'],
        'FJ' => ['name' => 'Fidji',              'prefix' => '+679', 'label' => 'FJI (+679)'],
        'PG' => ['name' => 'Papouasie-N.-Guinée', 'prefix' => '+675', 'label' => 'PNG (+675)'],
    ],
];
