<?php

return [
    /*
     * Liste d'emails autorisés à recevoir les alertes "nouveau lead cabinet".
     * Format env: FAYEKU_ADMIN_EMAILS=alice@fayeku.sn,bob@fayeku.sn
     */
    'admin_emails' => array_values(array_filter(array_map(
        'trim',
        explode(',', (string) env('FAYEKU_ADMIN_EMAILS', ''))
    ))),

    'otp_expiry_minutes' => (int) env('OTP_EXPIRY_MINUTES', 10),
    'otp_max_attempts' => (int) env('OTP_MAX_ATTEMPTS', 3),
    'otp_bypass_code' => env('OTP_BYPASS_CODE'),
    // Canal de livraison OTP : `whatsapp` (défaut, en attendant la validation
    // Orange IAM) ou `sms` (Orange SMS, à activer une fois le compte validé).
    'otp_channel' => env('OTP_CHANNEL', 'whatsapp'),
    'fne_api_url' => env('FNE_API_URL', ''),
    'fne_test_url' => env('FNE_TEST_URL', 'http://54.247.95.108/ws'),
    'countries' => [
        'SN' => ['name' => 'Sénégal',       'prefix' => '+221', 'label' => 'SEN (+221)'],
        'CI' => ['name' => "Côte d'Ivoire", 'prefix' => '+225', 'label' => 'CIV (+225)'],
    ],

    'phone_countries' => [
        // ── Afrique de l'Ouest (CEDEAO) ──
        'SN' => ['name' => 'Sénégal',           'prefix' => '+221', 'label' => 'SEN (+221)', 'format' => '+221 XX XXX XX XX'],
        'CI' => ['name' => "Côte d'Ivoire",     'prefix' => '+225', 'label' => 'CIV (+225)', 'format' => '+225 XX XX XX XXXX'],
        'ML' => ['name' => 'Mali',               'prefix' => '+223', 'label' => 'MLI (+223)', 'format' => '+223 XX XX XX XX'],
        'GN' => ['name' => 'Guinée',             'prefix' => '+224', 'label' => 'GIN (+224)', 'format' => '+224 XXX XX XX XX'],
        'BF' => ['name' => 'Burkina Faso',       'prefix' => '+226', 'label' => 'BFA (+226)', 'format' => '+226 XX XX XX XX'],
        'NE' => ['name' => 'Niger',              'prefix' => '+227', 'label' => 'NER (+227)', 'format' => '+227 XX XX XX XX'],
        'TG' => ['name' => 'Togo',               'prefix' => '+228', 'label' => 'TGO (+228)', 'format' => '+228 XX XX XX XX'],
        'BJ' => ['name' => 'Bénin',              'prefix' => '+229', 'label' => 'BEN (+229)', 'format' => '+229 XX XX XX XX XX'],
        'MR' => ['name' => 'Mauritanie',         'prefix' => '+222', 'label' => 'MRT (+222)', 'format' => '+222 XX XX XX XX'],
        'GH' => ['name' => 'Ghana',              'prefix' => '+233', 'label' => 'GHA (+233)', 'format' => '+233 XX XXX XXXX'],
        'NG' => ['name' => 'Nigeria',            'prefix' => '+234', 'label' => 'NGA (+234)', 'format' => '+234 XXX XXX XXXX'],
        'GM' => ['name' => 'Gambie',             'prefix' => '+220', 'label' => 'GMB (+220)', 'format' => '+220 XXX XXXX'],
        'GW' => ['name' => 'Guinée-Bissau',      'prefix' => '+245', 'label' => 'GNB (+245)', 'format' => '+245 XXX XXX XXX'],
        'SL' => ['name' => 'Sierra Leone',       'prefix' => '+232', 'label' => 'SLE (+232)', 'format' => '+232 XX XXXXXX'],
        'LR' => ['name' => 'Liberia',            'prefix' => '+231', 'label' => 'LBR (+231)', 'format' => '+231 XX XXX XXXX'],
        'CV' => ['name' => 'Cap-Vert',           'prefix' => '+238', 'label' => 'CPV (+238)', 'format' => '+238 XXX XX XX'],

        // ── Afrique Centrale ──
        'CM' => ['name' => 'Cameroun',           'prefix' => '+237', 'label' => 'CMR (+237)', 'format' => '+237 X XX XX XX XX'],
        'GA' => ['name' => 'Gabon',              'prefix' => '+241', 'label' => 'GAB (+241)', 'format' => '+241 XX XX XX XX'],
        'CG' => ['name' => 'Congo-Brazzaville',  'prefix' => '+242', 'label' => 'COG (+242)', 'format' => '+242 XX XXX XXXX'],
        'CD' => ['name' => 'Congo-Kinshasa',     'prefix' => '+243', 'label' => 'COD (+243)', 'format' => '+243 XXX XXX XXX'],
        'CF' => ['name' => 'Centrafrique',       'prefix' => '+236', 'label' => 'CAF (+236)', 'format' => '+236 XX XX XX XX'],
        'TD' => ['name' => 'Tchad',              'prefix' => '+235', 'label' => 'TCD (+235)', 'format' => '+235 XX XX XX XX'],
        'GQ' => ['name' => 'Guinée équatoriale', 'prefix' => '+240', 'label' => 'GNQ (+240)', 'format' => '+240 XXX XXX XXX'],
        'ST' => ['name' => 'Sao Tomé-et-Principe', 'prefix' => '+239', 'label' => 'STP (+239)', 'format' => '+239 XX XXXXX'],

        // ── Afrique de l'Est ──
        'KE' => ['name' => 'Kenya',              'prefix' => '+254', 'label' => 'KEN (+254)', 'format' => '+254 XXX XXXXXX'],
        'TZ' => ['name' => 'Tanzanie',           'prefix' => '+255', 'label' => 'TZA (+255)', 'format' => '+255 XXX XXX XXX'],
        'UG' => ['name' => 'Ouganda',            'prefix' => '+256', 'label' => 'UGA (+256)', 'format' => '+256 XXX XXXXXX'],
        'RW' => ['name' => 'Rwanda',             'prefix' => '+250', 'label' => 'RWA (+250)', 'format' => '+250 XXX XXX XXX'],
        'BI' => ['name' => 'Burundi',            'prefix' => '+257', 'label' => 'BDI (+257)', 'format' => '+257 XX XX XXXX'],
        'ET' => ['name' => 'Éthiopie',           'prefix' => '+251', 'label' => 'ETH (+251)', 'format' => '+251 XX XXX XXXX'],
        'DJ' => ['name' => 'Djibouti',           'prefix' => '+253', 'label' => 'DJI (+253)', 'format' => '+253 XX XX XX XX'],
        'SO' => ['name' => 'Somalie',            'prefix' => '+252', 'label' => 'SOM (+252)', 'format' => '+252 XX XXX XXX'],
        'ER' => ['name' => 'Érythrée',           'prefix' => '+291', 'label' => 'ERI (+291)', 'format' => '+291 X XXX XXX'],
        'SD' => ['name' => 'Soudan',             'prefix' => '+249', 'label' => 'SDN (+249)', 'format' => '+249 XX XXX XXXX'],
        'SS' => ['name' => 'Soudan du Sud',      'prefix' => '+211', 'label' => 'SSD (+211)', 'format' => '+211 XX XXX XXXX'],

        // ── Afrique Australe ──
        'ZA' => ['name' => 'Afrique du Sud',     'prefix' => '+27',  'label' => 'ZAF (+27)',  'format' => '+27 XX XXX XXXX'],
        'MZ' => ['name' => 'Mozambique',         'prefix' => '+258', 'label' => 'MOZ (+258)', 'format' => '+258 XX XXX XXXX'],
        'ZM' => ['name' => 'Zambie',             'prefix' => '+260', 'label' => 'ZMB (+260)', 'format' => '+260 XX XXX XXXX'],
        'ZW' => ['name' => 'Zimbabwe',           'prefix' => '+263', 'label' => 'ZWE (+263)', 'format' => '+263 XX XXX XXXX'],
        'MW' => ['name' => 'Malawi',             'prefix' => '+265', 'label' => 'MWI (+265)', 'format' => '+265 X XXXX XXXX'],
        'BW' => ['name' => 'Botswana',           'prefix' => '+267', 'label' => 'BWA (+267)', 'format' => '+267 XX XXX XXX'],
        'NA' => ['name' => 'Namibie',            'prefix' => '+264', 'label' => 'NAM (+264)', 'format' => '+264 XX XXX XXXX'],
        'SZ' => ['name' => 'Eswatini',           'prefix' => '+268', 'label' => 'SWZ (+268)', 'format' => '+268 XX XX XXXX'],
        'LS' => ['name' => 'Lesotho',            'prefix' => '+266', 'label' => 'LSO (+266)', 'format' => '+266 XXXX XXXX'],
        'AO' => ['name' => 'Angola',             'prefix' => '+244', 'label' => 'AGO (+244)', 'format' => '+244 XXX XXX XXX'],
        'MG' => ['name' => 'Madagascar',         'prefix' => '+261', 'label' => 'MDG (+261)', 'format' => '+261 XX XX XXX XX'],
        'MU' => ['name' => 'Maurice',            'prefix' => '+230', 'label' => 'MUS (+230)', 'format' => '+230 XXXX XXXX'],
        'KM' => ['name' => 'Comores',            'prefix' => '+269', 'label' => 'COM (+269)', 'format' => '+269 XXX XX XX'],
        'SC' => ['name' => 'Seychelles',         'prefix' => '+248', 'label' => 'SYC (+248)', 'format' => '+248 X XX XX XX'],

        // ── Afrique du Nord ──
        'MA' => ['name' => 'Maroc',              'prefix' => '+212', 'label' => 'MAR (+212)', 'format' => '+212 XXX-XXXXXX'],
        'DZ' => ['name' => 'Algérie',            'prefix' => '+213', 'label' => 'DZA (+213)', 'format' => '+213 XXX XX XX XX'],
        'TN' => ['name' => 'Tunisie',            'prefix' => '+216', 'label' => 'TUN (+216)', 'format' => '+216 XX XXX XXX'],
        'LY' => ['name' => 'Libye',              'prefix' => '+218', 'label' => 'LBY (+218)', 'format' => '+218 XX-XXXXXXX'],
        'EG' => ['name' => 'Égypte',             'prefix' => '+20',  'label' => 'EGY (+20)',  'format' => '+20 XX XXXXXXXX'],

        // ── Europe ──
        'FR' => ['name' => 'France',             'prefix' => '+33',  'label' => 'FRA (+33)',  'format' => '+33 X XX XX XX XX'],
        'BE' => ['name' => 'Belgique',           'prefix' => '+32',  'label' => 'BEL (+32)',  'format' => '+32 XXX XX XX XX'],
        'CH' => ['name' => 'Suisse',             'prefix' => '+41',  'label' => 'CHE (+41)',  'format' => '+41 XX XXX XX XX'],
        'ES' => ['name' => 'Espagne',            'prefix' => '+34',  'label' => 'ESP (+34)',  'format' => '+34 XXX XX XX XX'],
        'PT' => ['name' => 'Portugal',           'prefix' => '+351', 'label' => 'PRT (+351)', 'format' => '+351 XXX XXX XXX'],
        'DE' => ['name' => 'Allemagne',          'prefix' => '+49',  'label' => 'DEU (+49)',  'format' => '+49 XXXX XXXXXXX'],
        'IT' => ['name' => 'Italie',             'prefix' => '+39',  'label' => 'ITA (+39)',  'format' => '+39 XXX XXX XXXX'],
        'GB' => ['name' => 'Royaume-Uni',        'prefix' => '+44',  'label' => 'GBR (+44)',  'format' => '+44 XXXX XXXXXX'],
        'NL' => ['name' => 'Pays-Bas',           'prefix' => '+31',  'label' => 'NLD (+31)',  'format' => '+31 X XXXXXXXX'],
        'LU' => ['name' => 'Luxembourg',         'prefix' => '+352', 'label' => 'LUX (+352)', 'format' => '+352 XXX XXX XXX'],
        'AT' => ['name' => 'Autriche',           'prefix' => '+43',  'label' => 'AUT (+43)',  'format' => '+43 XXX XXXXXX'],
        'IE' => ['name' => 'Irlande',            'prefix' => '+353', 'label' => 'IRL (+353)', 'format' => '+353 XX XXX XXXX'],
        'SE' => ['name' => 'Suède',              'prefix' => '+46',  'label' => 'SWE (+46)',  'format' => '+46 XX XXX XX XX'],
        'NO' => ['name' => 'Norvège',            'prefix' => '+47',  'label' => 'NOR (+47)',  'format' => '+47 XXX XX XXX'],
        'DK' => ['name' => 'Danemark',           'prefix' => '+45',  'label' => 'DNK (+45)',  'format' => '+45 XX XX XX XX'],
        'FI' => ['name' => 'Finlande',           'prefix' => '+358', 'label' => 'FIN (+358)', 'format' => '+358 XX XXX XXXX'],
        'PL' => ['name' => 'Pologne',            'prefix' => '+48',  'label' => 'POL (+48)',  'format' => '+48 XXX XXX XXX'],
        'CZ' => ['name' => 'Tchéquie',           'prefix' => '+420', 'label' => 'CZE (+420)', 'format' => '+420 XXX XXX XXX'],
        'RO' => ['name' => 'Roumanie',           'prefix' => '+40',  'label' => 'ROU (+40)',  'format' => '+40 XXX XXX XXX'],
        'GR' => ['name' => 'Grèce',              'prefix' => '+30',  'label' => 'GRC (+30)',  'format' => '+30 XXX XXX XXXX'],
        'HU' => ['name' => 'Hongrie',            'prefix' => '+36',  'label' => 'HUN (+36)',  'format' => '+36 XX XXX XXXX'],
        'HR' => ['name' => 'Croatie',            'prefix' => '+385', 'label' => 'HRV (+385)', 'format' => '+385 XX XXX XXXX'],
        'BG' => ['name' => 'Bulgarie',           'prefix' => '+359', 'label' => 'BGR (+359)', 'format' => '+359 XX XXX XXXX'],
        'SK' => ['name' => 'Slovaquie',          'prefix' => '+421', 'label' => 'SVK (+421)', 'format' => '+421 XXX XXX XXX'],
        'SI' => ['name' => 'Slovénie',           'prefix' => '+386', 'label' => 'SVN (+386)', 'format' => '+386 XX XXX XXX'],
        'RS' => ['name' => 'Serbie',             'prefix' => '+381', 'label' => 'SRB (+381)', 'format' => '+381 XX XXX XXXX'],
        'BA' => ['name' => 'Bosnie-Herzégovine', 'prefix' => '+387', 'label' => 'BIH (+387)', 'format' => '+387 XX XXX-XXX'],
        'AL' => ['name' => 'Albanie',            'prefix' => '+355', 'label' => 'ALB (+355)', 'format' => '+355 XX XXX XXXX'],
        'MK' => ['name' => 'Macédoine du Nord',  'prefix' => '+389', 'label' => 'MKD (+389)', 'format' => '+389 XX XXX XXX'],
        'ME' => ['name' => 'Monténégro',         'prefix' => '+382', 'label' => 'MNE (+382)', 'format' => '+382 XX XXX XXX'],
        'MD' => ['name' => 'Moldavie',           'prefix' => '+373', 'label' => 'MDA (+373)', 'format' => '+373 XXXX XXXX'],
        'UA' => ['name' => 'Ukraine',            'prefix' => '+380', 'label' => 'UKR (+380)', 'format' => '+380 XX XXX XX XX'],
        'BY' => ['name' => 'Biélorussie',        'prefix' => '+375', 'label' => 'BLR (+375)', 'format' => '+375 XX XXX-XX-XX'],
        'RU' => ['name' => 'Russie',             'prefix' => '+7',   'label' => 'RUS (+7)',   'format' => '+7 XXX XXX-XX-XX'],
        'TR' => ['name' => 'Turquie',            'prefix' => '+90',  'label' => 'TUR (+90)',  'format' => '+90 XXX XXX XXXX'],
        'CY' => ['name' => 'Chypre',             'prefix' => '+357', 'label' => 'CYP (+357)', 'format' => '+357 XX XXXXXX'],
        'MT' => ['name' => 'Malte',              'prefix' => '+356', 'label' => 'MLT (+356)', 'format' => '+356 XXXX XXXX'],
        'IS' => ['name' => 'Islande',            'prefix' => '+354', 'label' => 'ISL (+354)', 'format' => '+354 XXX XXXX'],
        'EE' => ['name' => 'Estonie',            'prefix' => '+372', 'label' => 'EST (+372)', 'format' => '+372 XXXX XXXX'],
        'LV' => ['name' => 'Lettonie',           'prefix' => '+371', 'label' => 'LVA (+371)', 'format' => '+371 XX XXX XXX'],
        'LT' => ['name' => 'Lituanie',           'prefix' => '+370', 'label' => 'LTU (+370)', 'format' => '+370 XXX XXXXX'],

        // ── Amérique du Nord ──
        'US' => ['name' => 'États-Unis',         'prefix' => '+1',   'label' => 'USA (+1)',   'format' => '+1 XXX-XXX-XXXX'],
        'CA' => ['name' => 'Canada',             'prefix' => '+1',   'label' => 'CAN (+1)',   'format' => '+1 XXX-XXX-XXXX'],
        'MX' => ['name' => 'Mexique',            'prefix' => '+52',  'label' => 'MEX (+52)',  'format' => '+52 XXX XXX XXXX'],

        // ── Amérique Centrale & Caraïbes ──
        'HT' => ['name' => 'Haïti',              'prefix' => '+509', 'label' => 'HTI (+509)', 'format' => '+509 XX XX XXXX'],
        'DO' => ['name' => 'Rép. dominicaine',   'prefix' => '+1',   'label' => 'DOM (+1)',   'format' => '+1 XXX-XXX-XXXX'],
        'CU' => ['name' => 'Cuba',               'prefix' => '+53',  'label' => 'CUB (+53)',  'format' => '+53 X XXXXXXX'],
        'JM' => ['name' => 'Jamaïque',           'prefix' => '+1',   'label' => 'JAM (+1)',   'format' => '+1 XXX-XXX-XXXX'],
        'TT' => ['name' => 'Trinité-et-Tobago',  'prefix' => '+1',   'label' => 'TTO (+1)',   'format' => '+1 XXX-XXX-XXXX'],
        'PA' => ['name' => 'Panama',             'prefix' => '+507', 'label' => 'PAN (+507)', 'format' => '+507 XXXX-XXXX'],
        'CR' => ['name' => 'Costa Rica',         'prefix' => '+506', 'label' => 'CRI (+506)', 'format' => '+506 XXXX XXXX'],
        'GT' => ['name' => 'Guatemala',          'prefix' => '+502', 'label' => 'GTM (+502)', 'format' => '+502 XXXX XXXX'],
        'HN' => ['name' => 'Honduras',           'prefix' => '+504', 'label' => 'HND (+504)', 'format' => '+504 XXXX-XXXX'],
        'SV' => ['name' => 'Salvador',           'prefix' => '+503', 'label' => 'SLV (+503)', 'format' => '+503 XXXX-XXXX'],
        'NI' => ['name' => 'Nicaragua',          'prefix' => '+505', 'label' => 'NIC (+505)', 'format' => '+505 XXXX XXXX'],

        // ── Amérique du Sud ──
        'BR' => ['name' => 'Brésil',             'prefix' => '+55',  'label' => 'BRA (+55)',  'format' => '+55 XX XXXXX-XXXX'],
        'AR' => ['name' => 'Argentine',          'prefix' => '+54',  'label' => 'ARG (+54)',  'format' => '+54 X XX XXXX-XXXX'],
        'CO' => ['name' => 'Colombie',           'prefix' => '+57',  'label' => 'COL (+57)',  'format' => '+57 XXX XXX XXXX'],
        'CL' => ['name' => 'Chili',              'prefix' => '+56',  'label' => 'CHL (+56)',  'format' => '+56 X XXXX XXXX'],
        'PE' => ['name' => 'Pérou',              'prefix' => '+51',  'label' => 'PER (+51)',  'format' => '+51 XXX XXX XXX'],
        'VE' => ['name' => 'Venezuela',          'prefix' => '+58',  'label' => 'VEN (+58)',  'format' => '+58 XXX-XXXXXXX'],
        'EC' => ['name' => 'Équateur',           'prefix' => '+593', 'label' => 'ECU (+593)', 'format' => '+593 XX XXX XXXX'],
        'BO' => ['name' => 'Bolivie',            'prefix' => '+591', 'label' => 'BOL (+591)', 'format' => '+591 X XXX XXXX'],
        'PY' => ['name' => 'Paraguay',           'prefix' => '+595', 'label' => 'PRY (+595)', 'format' => '+595 XXX XXX XXX'],
        'UY' => ['name' => 'Uruguay',            'prefix' => '+598', 'label' => 'URY (+598)', 'format' => '+598 XX XXX XXX'],
        'GY' => ['name' => 'Guyana',             'prefix' => '+592', 'label' => 'GUY (+592)', 'format' => '+592 XXX XXXX'],
        'SR' => ['name' => 'Suriname',           'prefix' => '+597', 'label' => 'SUR (+597)', 'format' => '+597 XXX-XXXX'],
        'GF' => ['name' => 'Guyane française',   'prefix' => '+594', 'label' => 'GUF (+594)', 'format' => '+594 XXX XX XX XX'],

        // ── Moyen-Orient ──
        'SA' => ['name' => 'Arabie saoudite',    'prefix' => '+966', 'label' => 'SAU (+966)', 'format' => '+966 XX XXX XXXX'],
        'AE' => ['name' => 'Émirats arabes unis', 'prefix' => '+971', 'label' => 'ARE (+971)', 'format' => '+971 XX XXX XXXX'],
        'QA' => ['name' => 'Qatar',              'prefix' => '+974', 'label' => 'QAT (+974)', 'format' => '+974 XXXX XXXX'],
        'KW' => ['name' => 'Koweït',             'prefix' => '+965', 'label' => 'KWT (+965)', 'format' => '+965 XXXX XXXX'],
        'BH' => ['name' => 'Bahreïn',            'prefix' => '+973', 'label' => 'BHR (+973)', 'format' => '+973 XXXX XXXX'],
        'OM' => ['name' => 'Oman',               'prefix' => '+968', 'label' => 'OMN (+968)', 'format' => '+968 XXXX XXXX'],
        'YE' => ['name' => 'Yémen',              'prefix' => '+967', 'label' => 'YEM (+967)', 'format' => '+967 XXX XXX XXX'],
        'IQ' => ['name' => 'Irak',               'prefix' => '+964', 'label' => 'IRQ (+964)', 'format' => '+964 XXX XXX XXXX'],
        'IR' => ['name' => 'Iran',               'prefix' => '+98',  'label' => 'IRN (+98)',  'format' => '+98 XXX XXX XXXX'],
        'JO' => ['name' => 'Jordanie',           'prefix' => '+962', 'label' => 'JOR (+962)', 'format' => '+962 X XXXX XXXX'],
        'LB' => ['name' => 'Liban',              'prefix' => '+961', 'label' => 'LBN (+961)', 'format' => '+961 XX XXX XXX'],
        'SY' => ['name' => 'Syrie',              'prefix' => '+963', 'label' => 'SYR (+963)', 'format' => '+963 XXX XXX XXX'],
        'PS' => ['name' => 'Palestine',          'prefix' => '+970', 'label' => 'PSE (+970)', 'format' => '+970 XXX XXX XXX'],
        'IL' => ['name' => 'Israël',             'prefix' => '+972', 'label' => 'ISR (+972)', 'format' => '+972 XX-XXX-XXXX'],

        // ── Asie ──
        'CN' => ['name' => 'Chine',              'prefix' => '+86',  'label' => 'CHN (+86)',  'format' => '+86 XXX XXXX XXXX'],
        'JP' => ['name' => 'Japon',              'prefix' => '+81',  'label' => 'JPN (+81)',  'format' => '+81 XX-XXXX-XXXX'],
        'KR' => ['name' => 'Corée du Sud',       'prefix' => '+82',  'label' => 'KOR (+82)',  'format' => '+82 XX-XXXX-XXXX'],
        'IN' => ['name' => 'Inde',               'prefix' => '+91',  'label' => 'IND (+91)',  'format' => '+91 XXXXX XXXXX'],
        'PK' => ['name' => 'Pakistan',           'prefix' => '+92',  'label' => 'PAK (+92)',  'format' => '+92 XXX XXXXXXX'],
        'BD' => ['name' => 'Bangladesh',         'prefix' => '+880', 'label' => 'BGD (+880)', 'format' => '+880 XXXX-XXXXXX'],
        'LK' => ['name' => 'Sri Lanka',          'prefix' => '+94',  'label' => 'LKA (+94)',  'format' => '+94 XX XXX XXXX'],
        'NP' => ['name' => 'Népal',              'prefix' => '+977', 'label' => 'NPL (+977)', 'format' => '+977 XXX-XXXXXXX'],
        'MM' => ['name' => 'Myanmar',            'prefix' => '+95',  'label' => 'MMR (+95)',  'format' => '+95 XXX XXX XXX'],
        'TH' => ['name' => 'Thaïlande',         'prefix' => '+66',  'label' => 'THA (+66)',  'format' => '+66 XX XXX XXXX'],
        'VN' => ['name' => 'Viêt Nam',           'prefix' => '+84',  'label' => 'VNM (+84)',  'format' => '+84 XX XXXX XXXX'],
        'KH' => ['name' => 'Cambodge',           'prefix' => '+855', 'label' => 'KHM (+855)', 'format' => '+855 XX XXX XXX'],
        'LA' => ['name' => 'Laos',               'prefix' => '+856', 'label' => 'LAO (+856)', 'format' => '+856 XX XXX XXX'],
        'MY' => ['name' => 'Malaisie',           'prefix' => '+60',  'label' => 'MYS (+60)',  'format' => '+60 XX-XXX XXXX'],
        'SG' => ['name' => 'Singapour',          'prefix' => '+65',  'label' => 'SGP (+65)',  'format' => '+65 XXXX XXXX'],
        'ID' => ['name' => 'Indonésie',          'prefix' => '+62',  'label' => 'IDN (+62)',  'format' => '+62 XXX-XXX-XXX'],
        'PH' => ['name' => 'Philippines',        'prefix' => '+63',  'label' => 'PHL (+63)',  'format' => '+63 XXX XXX XXXX'],
        'TW' => ['name' => 'Taïwan',             'prefix' => '+886', 'label' => 'TWN (+886)', 'format' => '+886 XXX XXX XXX'],
        'HK' => ['name' => 'Hong Kong',          'prefix' => '+852', 'label' => 'HKG (+852)', 'format' => '+852 XXXX XXXX'],
        'MN' => ['name' => 'Mongolie',           'prefix' => '+976', 'label' => 'MNG (+976)', 'format' => '+976 XX XX XXXX'],
        'AF' => ['name' => 'Afghanistan',        'prefix' => '+93',  'label' => 'AFG (+93)',  'format' => '+93 XXX XXX XXXX'],
        'UZ' => ['name' => 'Ouzbékistan',        'prefix' => '+998', 'label' => 'UZB (+998)', 'format' => '+998 XX XXX XX XX'],
        'KZ' => ['name' => 'Kazakhstan',         'prefix' => '+7',   'label' => 'KAZ (+7)',   'format' => '+7 XXX XXX XXXX'],
        'GE' => ['name' => 'Géorgie',            'prefix' => '+995', 'label' => 'GEO (+995)', 'format' => '+995 XXX XXX XXX'],
        'AM' => ['name' => 'Arménie',            'prefix' => '+374', 'label' => 'ARM (+374)', 'format' => '+374 XX XXXXXX'],
        'AZ' => ['name' => 'Azerbaïdjan',        'prefix' => '+994', 'label' => 'AZE (+994)', 'format' => '+994 XX XXX XX XX'],

        // ── Océanie ──
        'AU' => ['name' => 'Australie',          'prefix' => '+61',  'label' => 'AUS (+61)',  'format' => '+61 XXX XXX XXX'],
        'NZ' => ['name' => 'Nouvelle-Zélande',   'prefix' => '+64',  'label' => 'NZL (+64)',  'format' => '+64 XX XXX XXXX'],
        'FJ' => ['name' => 'Fidji',              'prefix' => '+679', 'label' => 'FJI (+679)', 'format' => '+679 XXX XXXX'],
        'PG' => ['name' => 'Papouasie-N.-Guinée', 'prefix' => '+675', 'label' => 'PNG (+675)', 'format' => '+675 XXX XXXX'],
    ],
];
