<?php

return [
    'site' => [
        'name' => 'Fayeku',
        'tagline' => 'Facturez proprement. Contrôlez votre trésorerie.',
        'description' => 'Fayeku aide les PME à se faire payer plus vite grâce à la facturation moderne, aux relances WhatsApp automatisées et à une collaboration fluide avec le cabinet comptable.',
        'url' => 'https://www.fayeku.sn',
        'locale' => 'fr_SN',
        'keywords' => [
            'facturation Sénégal',
            'relance facture WhatsApp',
            'impayés PME',
            'plateforme comptable',
            'facture électronique',
            'DGID',
            'trésorerie PME Dakar',
            'cabinet comptable Dakar',
        ],
        'social' => [
            'linkedin' => 'https://www.linkedin.com/company/fayeku',
            'whatsapp' => 'https://wa.me/221700000000',
            'x' => 'https://x.com/fayeku',
        ],
        'contact' => [
            'email' => 'contact@fayeku.sn',
            'sales_email' => 'sales@fayeku.sn',
            'phone' => '+221 77 445 76 32',
            'address' => 'Villa N°71, Cité Chérif Macky Sall, Guédiawaye, Sénégal',
        ],
        'legal' => [
            'editor' => 'CISS IBRAHIMA',
            'company' => 'KHALIL SOFTWARES',
            'ninea' => '007524194',
            'rccm' => 'SN DKR 2019 A 25527',
        ],
    ],
    'navigation' => [
        ['href' => '/entreprises/', 'label' => 'Entreprises'],
        ['href' => '/experts-comptables/', 'label' => 'Experts-comptables'],
        ['href' => '/pricing/', 'label' => 'Tarifs'],
        ['href' => '/conformite/', 'label' => 'Conformité'],
        ['href' => '/contact/', 'label' => 'Contact'],
    ],
    'legal_links' => [
        ['href' => '/mentions-legales/', 'label' => 'Mentions légales'],
        ['href' => '/confidentialite/', 'label' => 'Confidentialité'],
    ],
    'home_personas' => [
        'entreprise' => [
            'badge' => null,
            'eyebrow' => 'Plateforme PME <-> cabinet comptable',
            'subtitle' => 'Fayeku connecte votre entreprise et votre comptable autour d une seule plateforme : factures conformes, relances WhatsApp automatiques et tresorerie visible a 90 jours.',
            'proof' => '2 mois d essai inclus sur chaque plan. Sans engagement. Resiliable a tout moment.',
            'primary_cta' => ['label' => 'Essayer 2 mois', 'href' => '/contact'],
            'secondary_cta' => ['label' => 'Voir les tarifs', 'href' => '/pricing'],
            'stat_title' => 'Mise en route',
            'stat_text' => 'Onboarding guide, sans configuration lourde, avec acces Fayeku Compta activable en quelques clics.',
            'image' => '/hero-dashboard.svg',
        ],
        'expert' => [
            'badge' => 'Fayeku Compta est gratuit',
            'eyebrow' => 'Cockpit multi-clients pour cabinets',
            'subtitle' => 'Centralisez les factures de vos PME clientes, collectez les pieces, exportez vers vos outils comptables et activez un programme partenaire recurrent.',
            'proof' => 'Cabinet gratuit. PMEs invitees via votre lien : 2 mois Essentiel offerts.',
            'primary_cta' => ['label' => 'Decouvrir Fayeku Compta', 'href' => '/experts-comptables'],
            'secondary_cta' => ['label' => 'Voir le programme partenaire', 'href' => '/experts-comptables#partenaires'],
            'stat_title' => 'Gain de temps immediat',
            'stat_text' => 'Accedez aux factures de vos clients en temps reel, exportez en un clic, sans ressaisie manuelle.',
            'image' => '/cabinet-dashboard.svg',
        ],
    ],
    'problem_points' => [
        'Factures encore creees sur Word ou Excel',
        'Relances manuelles sur WhatsApp ou par telephone',
        'Pieces comptables envoyees en vrac en fin de mois',
        'Tresorerie floue et retards de paiement difficiles a anticiper',
    ],
    'value_cards' => [
        [
            'icon' => 'bolt',
            'title' => 'Se faire payer plus vite',
            'description' => 'Relances WhatsApp automatisees, suivi des impayes en temps reel, et messages prets a envoyer.',
        ],
        [
            'icon' => 'chart-bar',
            'title' => 'Controler le cash',
            'description' => 'Delai moyen de paiement, prevision de tresorerie a 90 jours et vision claire de l argent a encaisser.',
        ],
        [
            'icon' => 'users',
            'title' => 'Travailler mieux avec son comptable',
            'description' => 'Acces cabinet, exports, coffre-fort documents. Moins de WhatsApp, plus de structure.',
        ],
    ],
    'steps' => [
        'Creez une facture en 30 secondes',
        'Envoyez-la par WhatsApp ou email',
        'Suivez les paiements et les retards',
        'Fayeku relance vos clients au bon moment, automatiquement',
    ],
    'feature_groups' => [
        ['icon' => 'document', 'value' => 'Facturation professionnelle', 'note' => 'Templates logo + NINEA + TVA'],
        ['icon' => 'eye', 'value' => 'Suivi impayes', 'note' => 'Vue en temps reel des factures en retard'],
        ['icon' => 'chat', 'value' => 'Relances WhatsApp automatiques', 'note' => 'Scenarios J+7, J+15 et manuels'],
        ['icon' => 'sparkles', 'value' => 'Relance intelligente IA', 'note' => 'Quand relancer et quel message envoyer'],
        ['icon' => 'star', 'value' => 'Score fiabilite client', 'note' => 'Priorisez les comptes les plus risques'],
        ['icon' => 'trending-up', 'value' => 'Prevision tresorerie 90 jours', 'note' => 'Encaissements attendus et alertes'],
        ['icon' => 'refresh', 'value' => 'Factures recurrentes & devis', 'note' => 'Signature devis et conversion instantanee'],
        ['icon' => 'archive', 'value' => 'Coffre-fort documents', 'note' => 'Collecte de pieces simple pour le cabinet'],
        ['icon' => 'shield', 'value' => 'Conformite DGID', 'note' => 'Integration des disponibilite officielle'],
    ],
    'cabinet_bullets' => [
        ['icon' => 'chart-bar', 'title' => 'Dashboard multi-clients', 'description' => 'Une vue consolidee de tous vos clients PME : statuts, retards et activite recente.'],
        ['icon' => 'eye', 'title' => 'Vue factures en temps reel', 'description' => 'Accedez aux factures de chaque client des leur creation, sans attendre la fin du mois.'],
        ['icon' => 'arrow-down', 'title' => 'Exports Sage 100 / EBP / Excel', 'description' => 'Exportez les ecritures en un clic vers votre logiciel comptable, sans ressaisie.'],
        ['icon' => 'inbox', 'title' => 'Collecte de pieces', 'description' => 'Vos clients deposent leurs pieces directement dans Fayeku. Fini les PDFs sur WhatsApp.'],
        ['icon' => 'document-check', 'title' => 'Rapport mensuel automatique', 'description' => 'Un recapitulatif mensuel par client genere automatiquement, pret a archiver.'],
        ['icon' => 'banknotes', 'title' => 'Commission recurrente partenaire', 'description' => 'Percevez 15% recurrent a vie sur chaque client PME que vous recommandez.'],
    ],
    'pricing_plans' => [
        [
            'slug' => 'basique',
            'name' => 'Basique',
            'price' => '10 000 FCFA/mois HT',
            'secondary_price' => '100 000 FCFA/an · 2 mois d essai',
            'promise' => 'Facturez proprement',
            'cta' => 'Choisir Basique',
            'href' => '/contact',
            'features' => [
                'Factures illimitees',
                '20 relances WhatsApp auto / mois',
                'Suivi des impayes + dashboard',
                'Historique clients',
                '2 utilisateurs',
                'Acces Fayeku Compta activable',
            ],
        ],
        [
            'slug' => 'essentiel',
            'name' => 'Essentiel',
            'price' => '20 000 FCFA/mois HT',
            'secondary_price' => '200 000 FCFA/an · 2 mois d essai',
            'promise' => 'Controlez votre tresorerie',
            'cta' => 'Choisir Essentiel',
            'href' => '/contact',
            'popular' => true,
            'features' => [
                'Relances illimitees',
                'Relance intelligente IA',
                'Score fiabilite client',
                'Prevision tresorerie 90 jours',
                'Devis + signature + devis -> facture',
                'Factures recurrentes',
                'Coffre-fort documents',
                'Support WhatsApp < 4h',
                'Conformite DGID des dispo officielle',
            ],
        ],
        [
            'slug' => 'entreprise',
            'name' => 'Entreprise',
            'price' => 'A partir de 70 000 FCFA/mois HT',
            'secondary_price' => 'Sur devis · 2 mois d essai',
            'promise' => 'Gerez votre groupe',
            'cta' => 'Nous contacter',
            'href' => '/contact',
            'features' => [
                'Multi-entites',
                'API + SSO',
                'Workflows validation interne',
                'Support dedie + SLA + formation',
                'Conformite DGID',
                'Accompagnement sur mesure',
            ],
        ],
    ],
    'pricing_summary_rows' => [
        ['label' => 'Prix mensuel', 'values' => ['basique' => '10 000 FCFA', 'essentiel' => '20 000 FCFA', 'entreprise' => 'A partir de 70 000 FCFA']],
        ['label' => 'Prix annuel', 'values' => ['basique' => '100 000 FCFA', 'essentiel' => '200 000 FCFA', 'entreprise' => 'Sur devis']],
        ['label' => 'Essai inclus', 'values' => ['basique' => '2 mois', 'essentiel' => '2 mois', 'entreprise' => '2 mois']],
        ['label' => 'Factures', 'values' => ['basique' => 'Illimitees', 'essentiel' => 'Illimitees', 'entreprise' => 'Illimitees']],
        ['label' => 'Relances WhatsApp automatiques', 'values' => ['basique' => 'Oui · 20/mois', 'essentiel' => 'Oui · Illimitees', 'entreprise' => 'Oui · Illimitees']],
        ['label' => 'Support', 'values' => ['basique' => 'Email', 'essentiel' => 'WhatsApp < 4h', 'entreprise' => 'Dedie']],
        ['label' => 'Acces Fayeku Compta', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
    ],
    'pricing_comparison_sections' => [
        [
            'title' => 'Limites d usage',
            'rows' => [
                ['label' => 'Factures / mois', 'values' => ['basique' => 'Illimitees', 'essentiel' => 'Illimitees', 'entreprise' => 'Illimitees']],
                ['label' => 'Clients', 'values' => ['basique' => '50 max', 'essentiel' => '150 max', 'entreprise' => 'Illimite']],
                ['label' => 'Utilisateurs', 'values' => ['basique' => '2', 'essentiel' => '3', 'entreprise' => 'Illimite + roles']],
                ['label' => 'Relances auto / mois', 'values' => ['basique' => '20', 'essentiel' => 'Illimitees', 'entreprise' => 'Illimitees']],
            ],
        ],
        [
            'title' => 'Facturation & devis',
            'rows' => [
                ['label' => 'Creation de factures', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Templates personnalisables (logo, NINEA)', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Devis professionnels', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Facturation recurrente automatique', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Conformite DGID (des disponibilite)', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
            ],
        ],
        [
            'title' => 'Recouvrement & paiement',
            'rows' => [
                ['label' => 'Marquer facture payee (Wave / OM / Cash)', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Dashboard impayes temps reel', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Relances WhatsApp J+7, J+15', 'values' => ['basique' => 'Oui · 20/mois', 'essentiel' => 'Oui · Illimitees', 'entreprise' => 'Oui · Illimitees']],
                ['label' => 'Relance intelligente', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
            ],
        ],
        [
            'title' => 'Pilotage & analytics',
            'rows' => [
                ['label' => 'Delai moyen de paiement', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Export Excel', 'values' => ['basique' => 'Oui', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Rapports avances', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
                ['label' => 'Tresorerie previsionnelle 90j', 'values' => ['basique' => 'Non', 'essentiel' => 'Oui', 'entreprise' => 'Oui']],
            ],
        ],
    ],
    'partner_program' => [
        'title' => 'Programme Partenaire Experts-Comptables',
        'description' => 'Recommandez Fayeku a vos clients et gagnez une commission recurrente, tant que vos clients restent actifs.',
        'bullets' => [
            '15% de commission mensuelle recurrente, a vie',
            'Bonus premiere signature : +1 mois de MRR',
            'Les PME invitees via votre lien recoivent 2 mois Essentiel offerts',
            'Versement : Wave le 5 du mois',
        ],
        'tiers' => [
            'Partner : 1 a 4 clients · acces Compta complet + suivi',
            'Gold : 5 a 14 clients · badge officiel + visibilite renforcee + leads',
            'Platinum : 15+ clients · visibilite premium + leads prioritaires + account manager',
        ],
    ],
    'partner_commission_rows' => [
        ['metric' => 'Commission mensuelle recurrente', 'value' => '15% sur tous les plans, pour toujours'],
        ['metric' => 'Bonus premiere signature', 'value' => '+1 mois MRR'],
        ['metric' => 'Trial PMEs invitees via lien comptable', 'value' => '2 mois Essentiel offerts'],
        ['metric' => 'Versement', 'value' => 'Wave le 5 du mois'],
    ],
    'portfolio_sizes' => ['1 a 20 dossiers', '21 a 50 dossiers', '51 a 100 dossiers', '101 a 250 dossiers', '250+ dossiers'],
    'regions' => ['Dakar', 'Thies', 'Saint-Louis', 'Diourbel', 'Kaolack', 'Ziguinchor', 'Tambacounda', 'Autre region'],
    'faq_items' => [
        ['question' => 'Puis-je utiliser Fayeku sans integrer Wave/Orange Money ?', 'answer' => 'Oui. Les paiements se font hors application. Vous pouvez marquer une facture comme payee via Wave, Orange Money, virement ou cash, puis Fayeku gere le suivi et les relances WhatsApp.'],
        ['question' => 'Fayeku remplace-t-il mon comptable ?', 'answer' => 'Non. Fayeku structure vos donnees, fluidifie les echanges avec le cabinet et reduit la collecte chaotique. Le cabinet reste au centre du conseil et de la production comptable.'],
        ['question' => 'Est-ce compatible avec Sage/EBP ?', 'answer' => 'Oui. Les exports Sage 100, EBP et Excel sont disponibles sur tous les plans payants, avec acces Fayeku Compta gratuit pour votre cabinet.'],
        ['question' => 'Puis-je tester Fayeku avant de m engager ?', 'answer' => 'Oui. Chaque plan Fayeku inclut 2 mois d essai pour vous laisser le temps de tester la facturation, les relances et la collaboration cabinet.'],
        ['question' => 'Quid de la conformite DGID ?', 'answer' => 'Fayeku integrera la conformite DGID des que le cadre officiel sera disponible. Les plans Essentiel et Entreprise sont prepares pour cette evolution, sans changement d usage pour vos equipes.'],
        ['question' => 'Ou est hebergee la plateforme ?', 'answer' => 'Sur une infrastructure cloud securisee a haute disponibilite, avec des acces controles pour votre equipe et votre cabinet.'],
    ],
    'testimonials' => [
        ['quote' => 'Nous avons reduit le temps passe sur les relances clients et les equipes voient enfin les retards en un coup d oeil.', 'name' => 'Awa D.', 'role' => 'Dirigeante, PME services'],
        ['quote' => 'Le cockpit cabinet simplifie la collecte de pieces et prepare beaucoup mieux la cloture mensuelle.', 'name' => 'Mamadou N.', 'role' => 'Expert-comptable partenaire'],
        ['quote' => 'Le plan Essentiel donne la visibilite cash qui manquait a nos equipes terrain et finance.', 'name' => 'Fatou K.', 'role' => 'DAF externalisee'],
    ],
    'dgid_roadmap_note' => 'La Loi de Finances 2025 a institue l obligation de facturation electronique au Senegal. Des publication des modalites techniques officielles, Fayeku integrera nativement la conformite DGID dans les plans Essentiel et Entreprise, sans surcout.',
    'legal_pages' => [
        'mentions-legales' => [
            'title' => 'Mentions légales',
            'description' => 'Informations légales du site fayeku.sn.',
            'sections' => [
                ['title' => 'Éditeur du site', 'body' => 'Le site fayeku.sn est édité par CISS IBRAHIMA, agissant sous le nom commercial KHALIL SOFTWARES, dont le siège est situé Villa N°71, Cité Chérif Macky Sall, Guédiawaye, Sénégal.'],
                ['title' => 'Identification', 'body' => 'NINEA : 007524194 — RCCM : SN DKR 2019 A 25527.'],
                ['title' => 'Contact', 'body' => 'Email : contact@fayeku.sn — Téléphone : +221 77 445 76 32.'],
                ['title' => 'Propriété intellectuelle', 'body' => 'Les contenus, marques, logos et maquettes présentés sur ce site sont protégés et ne peuvent pas être réutilisés sans autorisation.'],
                ['title' => 'Hébergement', 'body' => 'Infrastructure cloud sécurisée à haute disponibilité. Détails disponibles sur demande à contact@fayeku.sn.'],
            ],
        ],
        'confidentialite' => [
            'title' => 'Confidentialite',
            'description' => 'Notre approche de la protection des donnees et des demandes commerciales.',
            'sections' => [
                ['title' => 'Donnees collectees', 'body' => 'Nous collectons uniquement les informations utiles au traitement des demandes de contact, d essai ou d onboarding.'],
                ['title' => 'Usage des donnees', 'body' => 'Ces donnees servent a vous recontacter, qualifier votre besoin et preparer votre mise en place Fayeku.'],
                ['title' => 'Vos droits', 'body' => 'Vous pouvez demander l acces, la correction ou la suppression de vos donnees en nous ecrivant a contact@fayeku.sn.'],
            ],
        ],
    ],
];
