<?php

return [
    'landings' => [
        'logiciel-facturation-senegal' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Logiciel de facturation Sénégal — Devis, factures, relances WhatsApp | Fayeku',
            'meta_description' => 'Le logiciel de facturation pensé pour les PME au Sénégal : devis, factures conformes, relances WhatsApp automatiques et collaboration cabinet comptable. 2 mois d’essai.',
            'eyebrow' => 'Logiciel de facturation Sénégal',
            'h1' => 'Logiciel de facturation pour PME au Sénégal',
            'subtitle' => 'Fayeku centralise vos devis, factures, paiements et relances dans une seule application pensée pour le marché sénégalais. Connecté à votre cabinet comptable, prêt pour la DGID.',
            'cta_primary' => ['label' => 'Essayer 2 mois', 'href' => '/contact'],
            'cta_secondary' => ['label' => 'Voir les tarifs', 'href' => '/pricing'],
            'proof_points' => [
                '2 mois d’essai sur tous les plans',
                'Wave & Orange Money supportés',
                'Conçu à Dakar, sans config lourde',
            ],
            'problems' => [
                'Vos factures sont créées dans Word ou Excel, sans suivi des paiements',
                'Vous relancez à la main, sur WhatsApp, et vous perdez des heures',
                'Votre trésorerie n’est claire qu’en fin de mois, quand il est déjà trop tard',
                'Votre comptable ne reçoit les pièces qu’en vrac, et la clôture prend des semaines',
            ],
            'features' => [
                ['title' => 'Devis & factures conformes', 'description' => 'Templates avec votre logo, NINEA, mentions TVA. Conversion devis → facture en un clic.'],
                ['title' => 'Relances WhatsApp automatiques', 'description' => 'Scénarios J+7, J+15 et messages prêts à envoyer. Vos clients reçoivent le bon rappel au bon moment.'],
                ['title' => 'Suivi des impayés en temps réel', 'description' => 'Dashboard avec les factures en retard, le délai moyen de paiement et les comptes à risque.'],
                ['title' => 'Prévision de trésorerie 90 jours', 'description' => 'Visualisez vos encaissements attendus et anticipez vos creux de cash.'],
                ['title' => 'Accès Fayeku Compta gratuit', 'description' => 'Invitez votre cabinet : exports Sage 100 / EBP / Excel, collecte de pièces, rapports mensuels.'],
                ['title' => 'Conformité DGID prête', 'description' => 'Préparée pour la facturation électronique obligatoire prévue par la Loi de Finances 2025.'],
            ],
            'use_cases' => [
                ['title' => 'Services & conseil', 'description' => 'Cabinets, agences, consultants : devis signés, factures récurrentes, relances multi-clients.'],
                ['title' => 'Commerce & distribution', 'description' => 'Factures B2B, suivi des règlements, alertes sur clients à risque.'],
                ['title' => 'BTP & terrain', 'description' => 'Factures de chantier, acomptes, exports comptables sans ressaisie.'],
            ],
            'faq' => [
                ['question' => 'Faut-il intégrer Wave ou Orange Money pour utiliser Fayeku ?', 'answer' => 'Non. Les paiements se font hors application. Vous marquez la facture comme payée (Wave, Orange Money, virement, cash) et Fayeku met à jour le suivi.'],
                ['question' => 'Mes factures sont-elles conformes aux mentions légales sénégalaises ?', 'answer' => 'Oui. Les templates intègrent votre NINEA, RCCM, taux TVA, conditions de paiement et toutes les mentions exigées.'],
                ['question' => 'Combien coûte le logiciel de facturation Fayeku ?', 'answer' => 'Le plan Basique démarre à 10 000 FCFA/mois HT (100 000 FCFA/an). Le plan Essentiel à 20 000 FCFA/mois. Chaque plan inclut 2 mois d’essai.'],
                ['question' => 'Mon comptable peut-il accéder à mes factures ?', 'answer' => 'Oui. Fayeku Compta est gratuit pour les cabinets : ils accèdent à vos factures en temps réel, collectent les pièces et exportent vers Sage / EBP.'],
                ['question' => 'Fayeku est-il prêt pour la facturation électronique DGID ?', 'answer' => 'Oui. Dès publication des modalités techniques officielles, Fayeku intégrera nativement la conformité DGID dans les plans Essentiel et Entreprise, sans surcoût.'],
            ],
        ],
        'logiciel-cabinet-comptable-senegal' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Logiciel pour cabinet comptable au Sénégal — Cockpit multi-clients gratuit | Fayeku',
            'meta_description' => 'Le logiciel pour cabinet comptable au Sénégal : cockpit multi-clients gratuit, collecte de pièces, exports Sage / EBP, commission partenaire récurrente 15 %.',
            'eyebrow' => 'Logiciel cabinet comptable Sénégal',
            'h1' => 'Logiciel pour cabinet comptable au Sénégal',
            'subtitle' => 'Fayeku Compta donne aux experts-comptables sénégalais un cockpit pour suivre toutes leurs PME clientes, collecter les pièces et activer un programme partenaire récurrent.',
            'cta_primary' => ['label' => 'Activer mon espace cabinet', 'href' => '/accountant/join'],
            'cta_secondary' => ['label' => 'Voir le programme partenaire', 'href' => '/accountants#partenaires'],
            'proof_points' => [
                'Cabinet gratuit — 0 FCFA à vie',
                '15 % de commission récurrente',
                'Exports Sage 100, EBP, Excel',
            ],
            'problems' => [
                'Vous courez après les pièces comptables sur WhatsApp à chaque fin de mois',
                'Vous ressaisissez les factures de vos clients dans Sage ou EBP',
                'Vos PME clientes utilisent toutes des outils différents (Word, Excel, vrac papier)',
                'Vous n’avez pas de canal récurrent pour développer votre portefeuille',
            ],
            'features' => [
                ['title' => 'Dashboard multi-clients', 'description' => 'Vue consolidée de toutes vos PME clientes : statuts, retards, activité récente.'],
                ['title' => 'Vue factures en temps réel', 'description' => 'Accédez aux factures de chaque client dès leur création, sans attendre la fin du mois.'],
                ['title' => 'Collecte de pièces structurée', 'description' => 'Vos clients déposent leurs pièces directement dans Fayeku. Fini les PDFs sur WhatsApp.'],
                ['title' => 'Exports Sage 100, EBP, Excel', 'description' => 'Exportez les écritures en un clic vers votre logiciel comptable, sans ressaisie.'],
                ['title' => 'Rapports mensuels automatiques', 'description' => 'Un récapitulatif mensuel par client, généré automatiquement et prêt à archiver.'],
                ['title' => 'Programme partenaire 15 %', 'description' => '15 % de commission mensuelle récurrente à vie sur chaque PME que vous recommandez.'],
            ],
            'use_cases' => [
                ['title' => 'Cabinets en croissance', 'description' => 'Gagnez du temps sur la production et libérez de la capacité pour le conseil.'],
                ['title' => 'Cabinets multi-sites', 'description' => 'Une seule plateforme pour tous les associés et collaborateurs.'],
                ['title' => 'Daf externalisés', 'description' => 'Une vision consolidée des PME que vous accompagnez, en temps réel.'],
            ],
            'faq' => [
                ['question' => 'Combien coûte Fayeku Compta pour mon cabinet ?', 'answer' => 'Fayeku Compta est gratuit, à vie, pour les cabinets d’expertise comptable au Sénégal. Aucune carte bancaire requise.'],
                ['question' => 'Comment fonctionne la commission partenaire ?', 'answer' => '15 % de commission mensuelle récurrente, à vie, sur chaque PME cliente recommandée. Versement Wave le 5 du mois.'],
                ['question' => 'Mes PME clientes doivent-elles payer ?', 'answer' => 'Les PME invitées via votre lien partenaire reçoivent 2 mois d’essai Essentiel offerts. Ensuite : 10 000 ou 20 000 FCFA/mois selon le plan.'],
                ['question' => 'Quels logiciels comptables sont supportés ?', 'answer' => 'Exports natifs Sage 100, EBP et Excel. Format adaptable sur demande pour vos outils internes.'],
                ['question' => 'Fayeku remplace-t-il le cabinet ?', 'answer' => 'Non. Fayeku structure les données des PME pour fluidifier les échanges avec le cabinet, qui reste au centre du conseil et de la production comptable.'],
            ],
        ],
        'facturation-electronique-dgid' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Facturation électronique DGID Sénégal — Loi de Finances 2025 | Fayeku',
            'meta_description' => 'Facturation électronique au Sénégal : ce que prévoit la Loi de Finances 2025, le calendrier DGID et comment Fayeku prépare PME et cabinets comptables à la conformité.',
            'eyebrow' => 'Conformité DGID',
            'h1' => 'Facturation électronique au Sénégal : ce que prévoit la DGID',
            'subtitle' => 'La Loi de Finances 2025 a institué l’obligation de facturation électronique. Fayeku intègre nativement la conformité dès la publication des modalités techniques officielles.',
            'cta_primary' => ['label' => 'Parler à un conseiller', 'href' => '/contact'],
            'cta_secondary' => ['label' => 'Voir le plan Essentiel', 'href' => '/pricing'],
            'proof_points' => [
                'Plans Essentiel & Entreprise prêts DGID',
                'Aucun surcoût à l’activation',
                'Templates conformes NINEA / TVA',
            ],
            'problems' => [
                'Vos factures Word ou Excel ne pourront pas être archivées ni transmises à la DGID',
                'Votre logiciel actuel n’a pas annoncé son plan de conformité',
                'Vous risquez de devoir tout refaire à la dernière minute',
                'Votre cabinet ne sait pas comment vous préparer',
            ],
            'features' => [
                ['title' => 'Factures conformes aux mentions DGID', 'description' => 'NINEA, RCCM, taux TVA, numérotation séquentielle : tout est intégré aux templates Fayeku.'],
                ['title' => 'Archivage électronique', 'description' => 'Vos factures sont stockées de manière sécurisée et horodatée, prêtes à être transmises.'],
                ['title' => 'Conformité activée sans surcoût', 'description' => 'Dès publication des modalités officielles, l’intégration sera déployée pour les plans Essentiel et Entreprise.'],
                ['title' => 'Accompagnement cabinet', 'description' => 'Votre comptable est inclus dans la boucle pour valider la conformité de votre paramétrage.'],
            ],
            'use_cases' => [
                ['title' => 'PME en croissance', 'description' => 'Préparez votre passage à la facture électronique sans interrompre votre activité.'],
                ['title' => 'Groupes multi-entités', 'description' => 'Centralisez la conformité de toutes vos filiales depuis une seule plateforme.'],
                ['title' => 'Cabinets comptables', 'description' => 'Accompagnez vos PME clientes dans leur mise en conformité avec un outil prêt.'],
            ],
            'faq' => [
                ['question' => 'Quelle est la date d’entrée en vigueur de la facturation électronique au Sénégal ?', 'answer' => 'La Loi de Finances 2025 a posé le cadre. Les modalités techniques officielles seront publiées par la DGID. Fayeku activera la conformité dès leur publication, sans surcoût pour les clients Essentiel et Entreprise.'],
                ['question' => 'Toutes les entreprises sont-elles concernées ?', 'answer' => 'Le périmètre exact sera précisé par les textes d’application. En pratique, toutes les entreprises assujetties à la TVA sont attendues comme concernées à terme.'],
                ['question' => 'Que faire si j’utilise encore Excel ou Word pour mes factures ?', 'answer' => 'C’est le bon moment pour migrer. Fayeku vous accompagne et vous fait passer sur un format conforme avant l’entrée en vigueur.'],
                ['question' => 'Y a-t-il un surcoût pour la conformité DGID ?', 'answer' => 'Non. La conformité DGID est incluse dans les plans Essentiel (20 000 FCFA/mois) et Entreprise. Aucun surcoût à l’activation.'],
            ],
        ],
        'logiciel-devis-facture-senegal' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Logiciel devis et facture Sénégal — Signature en ligne, conversion en 1 clic | Fayeku',
            'meta_description' => 'Logiciel de devis et facture au Sénégal : créez vos devis, faites-les signer en ligne et convertissez-les en factures en un clic. 2 mois d’essai sur Fayeku.',
            'eyebrow' => 'Devis & factures',
            'h1' => 'Logiciel de devis et facture pour PME au Sénégal',
            'subtitle' => 'Créez des devis professionnels, faites-les signer en ligne, convertissez-les en factures et relancez automatiquement vos clients depuis Fayeku.',
            'cta_primary' => ['label' => 'Essayer 2 mois', 'href' => '/contact'],
            'cta_secondary' => ['label' => 'Voir les tarifs', 'href' => '/pricing'],
            'proof_points' => [
                'Signature électronique des devis',
                'Conversion devis → facture en 1 clic',
                'Templates conformes Sénégal',
            ],
            'problems' => [
                'Vous créez vos devis dans Word puis vous les ressaisissez en factures',
                'Vos clients oublient de signer vos devis',
                'Vous perdez du temps à relancer pour la validation',
                'Vous n’avez pas de suivi clair des devis en attente',
            ],
            'features' => [
                ['title' => 'Devis professionnels', 'description' => 'Templates avec votre logo, NINEA et mentions légales, prêts à envoyer en quelques minutes.'],
                ['title' => 'Signature électronique', 'description' => 'Vos clients signent en un clic, sur mobile ou ordinateur. Notification immédiate.'],
                ['title' => 'Conversion en facture', 'description' => 'Un devis signé devient une facture en un clic. Sans ressaisie, sans erreur.'],
                ['title' => 'Suivi des devis en attente', 'description' => 'Dashboard des devis envoyés, signés, refusés. Relances automatiques possibles.'],
                ['title' => 'Factures récurrentes', 'description' => 'Pour vos abonnements et contrats, automatisez la création mensuelle des factures.'],
            ],
            'faq' => [
                ['question' => 'La signature électronique est-elle valable juridiquement ?', 'answer' => 'Oui. Fayeku enregistre l’horodatage, l’IP et l’identité du signataire. Le devis signé sert de preuve d’accord commercial.'],
                ['question' => 'Puis-je modifier un devis après envoi ?', 'answer' => 'Oui, tant qu’il n’est pas signé. Une fois signé, le devis est verrouillé pour preuve.'],
                ['question' => 'Combien de devis puis-je créer ?', 'answer' => 'Devis illimités sur les plans Essentiel et Entreprise. Disponible aussi sur Basique.'],
            ],
        ],
        'relance-facture-impayee-whatsapp' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Relance facture impayée par WhatsApp — Automatisée et personnalisée | Fayeku',
            'meta_description' => 'Relancez vos factures impayées par WhatsApp automatiquement avec Fayeku : scénarios J+7, J+15, messages personnalisés. Récupérez votre cash sans braquer la relation.',
            'eyebrow' => 'Recouvrement WhatsApp',
            'h1' => 'Relance facture impayée par WhatsApp — Automatisée',
            'subtitle' => 'Fayeku relance vos clients par WhatsApp automatiquement, au bon moment et avec le bon message, pour récupérer votre cash sans dégrader la relation commerciale.',
            'cta_primary' => ['label' => 'Tester gratuitement', 'href' => '/contact'],
            'cta_secondary' => ['label' => 'Voir les tarifs', 'href' => '/pricing'],
            'proof_points' => [
                'Scénarios J+7, J+15, J+30',
                'Messages WhatsApp personnalisables',
                'Score fiabilité client par IA',
            ],
            'problems' => [
                'Vous relancez à la main et vous perdez des heures',
                'Vos clients vous trouvent trop insistants ou pas assez',
                'Vous oubliez certains impayés',
                'Vous ne savez pas quel client relancer en priorité',
            ],
            'features' => [
                ['title' => 'Relances automatiques WhatsApp', 'description' => 'Scénarios J+7, J+15, J+30. Vos clients reçoivent le bon message, automatiquement.'],
                ['title' => 'Messages personnalisables', 'description' => 'Adaptez le ton selon la relation client : courtois, ferme, urgent. Templates prêts à l’emploi.'],
                ['title' => 'Relance intelligente IA', 'description' => 'L’IA Fayeku analyse l’historique de paiement et suggère quand relancer et quel message envoyer.'],
                ['title' => 'Score fiabilité client', 'description' => 'Identifiez automatiquement les comptes à risque pour les prioriser.'],
                ['title' => 'Suivi des relances envoyées', 'description' => 'Historique complet de vos relances WhatsApp et emails, avec accusés de réception.'],
            ],
            'faq' => [
                ['question' => 'Combien de relances WhatsApp puis-je envoyer par mois ?', 'answer' => 'Plan Basique : 20 relances WhatsApp automatiques par mois. Plans Essentiel et Entreprise : illimitées.'],
                ['question' => 'Mes clients voient-ils que c’est automatisé ?', 'answer' => 'Non. Les messages partent depuis votre numéro et sont personnalisés avec le nom du client, le montant et l’ancienneté de la facture.'],
                ['question' => 'Est-ce que la relance intelligente fonctionne sur tous les plans ?', 'answer' => 'La relance intelligente IA est incluse dans les plans Essentiel et Entreprise.'],
            ],
        ],
        'alternative-sage-senegal' => [
            'page_type' => 'seo-software',
            'meta_title' => 'Alternative à Sage 100 au Sénégal — Logiciel facturation moderne | Fayeku',
            'meta_description' => 'Cherchez une alternative à Sage 100 au Sénégal ? Fayeku est un logiciel de facturation moderne pour PME, connecté à votre cabinet comptable, avec exports Sage natifs.',
            'eyebrow' => 'Alternative Sage 100',
            'h1' => 'Alternative à Sage 100 pour les PME au Sénégal',
            'subtitle' => 'Fayeku est une alternative moderne à Sage 100 pour les PME : interface mobile, relances WhatsApp, prévisions de trésorerie — et exports natifs Sage pour votre cabinet.',
            'cta_primary' => ['label' => 'Comparer les tarifs', 'href' => '/pricing'],
            'cta_secondary' => ['label' => 'Parler à un conseiller', 'href' => '/contact'],
            'proof_points' => [
                'Exports Sage 100, EBP, Excel natifs',
                'Interface mobile et collaborative',
                'Conçu pour le Sénégal',
            ],
            'features' => [
                ['title' => 'Pas d’installation ni de licence lourde', 'description' => 'Fayeku est 100 % en ligne, accessible depuis n’importe quel navigateur ou mobile.'],
                ['title' => 'Interface pensée mobile', 'description' => 'Créez vos factures et relancez vos clients depuis votre téléphone, en déplacement.'],
                ['title' => 'Exports Sage 100 natifs', 'description' => 'Votre cabinet récupère les écritures comptables au format Sage en un clic.'],
                ['title' => 'Relances WhatsApp', 'description' => 'Là où Sage s’arrête, Fayeku continue : relances automatiques, suivi des paiements, IA.'],
                ['title' => 'Tarification PME', 'description' => 'À partir de 10 000 FCFA/mois HT, sans engagement, avec 2 mois d’essai.'],
            ],
            'faq' => [
                ['question' => 'Fayeku remplace-t-il complètement Sage 100 ?', 'answer' => 'Pour la partie facturation, suivi des paiements et relances : oui. Pour la comptabilité générale, votre cabinet continue d’utiliser Sage et reçoit les exports de Fayeku.'],
                ['question' => 'Mon cabinet est habitué à Sage. Va-t-il pouvoir continuer ?', 'answer' => 'Oui. Fayeku exporte vos écritures au format Sage 100 (et EBP, et Excel) pour que votre cabinet n’ait rien à changer.'],
                ['question' => 'Est-ce moins cher que Sage 100 ?', 'answer' => 'Oui. Pas de licence ni d’installation. Fayeku démarre à 10 000 FCFA/mois HT, contre des licences Sage généralement bien plus coûteuses.'],
            ],
        ],
    ],
];
